name: flutter_wrapper
version: 1.0.0+1
description: Flutter WebView wrapper app.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.7.0
  url_launcher: 6.2.6
  connectivity_plus: 6.0.3
  firebase_core: 2.27.0
  firebase_messaging: 14.7.19
  app_links: 6.1.1
  shared_preferences: 2.2.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  flutter_native_splash: 2.4.1
  flutter_launcher_icons: 0.13.1
